name: Laravel Deployment Action
description: A currently opinionated github action for deploying laravel apps
author: 'Séan Poynter-Smith'
branding:
  icon: 'send'
  color: 'green'

inputs:
  DEPLOY_KEY:
    description: 'SSH key for deploying, Should be added as a **secret**'
    required: true
  SERVER_IP:
    description: 'IP address of the server being deployed to, Should be added as a **secret**'
    required: true
  SERVER_PORT:
    description: 'Custom port for ssh and rsync'
    default: 22
  SSH_USER:
    description: 'required, used for SSH and deployment path if APP_PATH not specified'
    required: true
  APP_NAME:
    description: 'required, used for deployment path if APP_PATH not specified'
    required: true
  APP_PATH:
    description: 'leave blank for /srv/users/<SSH_USER>/apps/<APP_NAME>'
    required: false
  COMPOSER_COMMAND:
    description: ''
    default: composer install --no-progress --optimize-autoloader
    required: false
  NODE_VERSION:
    description: 'version of node to install'
    default: 16.14
    required: false
  NPM_INSTALL_COMMAND:
    description: 'requires package-lock.json to be present'
    default: npm ci --quiet
    required: false
  BUILD_COMMAND:
    description: 'build process command'
    default: npm run dev
    required: false
  ARTISAN_COMMANDS:
    description: 'commands to run on server with prefix'
    default: php artisan inspire
    required: false

runs:
  using: "composite"
  steps:
    - name: Set the APP_PATH environment variable
      id: step_one
      if: ${{ inputs.APP_PATH == '' }}
      shell: bash
      run: |
        echo "APP_PATH=/srv/users/${{inputs.SSH_USER}}/apps/${{inputs.APP_NAME}}" >> $GITHUB_ENV
        
    - name: Use the value
      id: step_two
      shell: bash
      run: |
        echo "${{ inputs.APP_PATH || env.APP_PATH }}" # This will output the path

    - name: Cache Composer dependencies
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.COMPOSER_COMMAND }}

    - name: Setup Node.js 16.14
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.NPM_INSTALL_COMMAND }}

    - name: NPM Build
      shell: bash
      run: ${{ inputs.BUILD_COMMAND }}

    - name: Sync
      env:
        dest: ${{inputs.SSH_USER}}@${{inputs.SERVER_IP}}:${{inputs.APP_PATH || env.APP_PATH}}
      shell: bash
      run: |
        echo "${{inputs.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -vzr --stats --checksum \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no -p ${{inputs.SERVER_PORT || 22}}' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          ./ ${{env.dest}}

    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.SERVER_IP }}
        username: ${{inputs.SSH_USER}}
        key: ${{ inputs.DEPLOY_KEY }}
        script: |
          cd ${{ inputs.APP_PATH || env.APP_PATH }}
          ${{ inputs.ARTISAN_COMMANDS }}

